/**
 * Generated by @zefiros/therefore@v0.0.1
 * Do not manually touch this
 */

/* eslint-disable */
import actionSchema from './schemas/action.schema.json'

import { Icon, Uri } from './icon.schema'

import AjvValidator from 'ajv'

export interface Action {
    /**
     * Tooltip for the main toolbar icon.
     */
    default_title: string
    /**
     * The popup appears when the user clicks the icon.
     */
    default_popup: Uri
    default_icon:
        | string
        | {
              '19': Icon
              '38': Icon
          }
}

export const Action = {
    schema: actionSchema,
    validate:
        typeof actionSchema === 'function'
            ? actionSchema
            : (new AjvValidator().compile(actionSchema) as {
                  (o: unknown | Action): o is Action
                  errors?: null | Array<import('ajv').ErrorObject>
              }),
    is: (o: unknown | Action): o is Action => Action.validate(o) === true,
    assert: (o: unknown | Action): asserts o is Action => {
        if (!Action.validate(o)) {
            throw new AjvValidator.ValidationError(Action.validate.errors ?? [])
        }
    },
}
