/**
 * Generated by @zefiros-software/therefore
 * eslint-disable
 */
"use strict";module.exports = validate10;module.exports.default = validate10;const schema11 = {"$schema":"http://json-schema.org/draft-07/schema#","enum":["captain","first mate","officer","ensign"]};function validate10(data, {instancePath="", parentData, parentDataProperty, rootData=data}={}){let vErrors = null;let errors = 0;if(!((((data === "captain") || (data === "first mate")) || (data === "officer")) || (data === "ensign"))){validate10.errors = [{instancePath,schemaPath:"#/enum",keyword:"enum",params:{allowedValues: schema11.enum},message:"must be equal to one of the allowed values"}];return false;}validate10.errors = vErrors;return errors === 0;}