/**
 * Generated by @zefiros/therefore@v0.0.1
 * Do not manually touch this
 */

/* eslint-disable */
import simpleSchema from './schemas/simple.schema.json'

import AjvValidator from 'ajv'

export type Simple = number | Simple[]

export const Simple = {
    schema: simpleSchema,
    validate: typeof simpleSchema === 'function' ? simpleSchema : new AjvValidator().compile<Simple>(simpleSchema),
    is: (o: unknown): o is Simple => Simple.validate(o) === true,
    assert: (o: unknown): asserts o is Simple => {
        if (!Simple.validate(o)) {
            throw new AjvValidator.ValidationError(Simple.validate.errors ?? [])
        }
    },
}
