/**
 * Generated by @zefiros/therefore@v0.0.1
 * Do not manually touch this
 */

/* eslint-disable */
import personSchema from './schemas/person.schema.json'

import AjvValidator from 'ajv'

export interface Person {
    /**
     * The person's first name.
     */
    firstName: string
    lastName: string
    age: number
}

export const Person = {
    schema: personSchema,
    validate: typeof personSchema === 'function' ? personSchema : new AjvValidator().compile<Person>(personSchema),
    is: (o: unknown): o is Person => Person.validate(o) === true,
    assert: (o: unknown): asserts o is Person => {
        if (!Person.validate(o)) {
            throw new AjvValidator.ValidationError(Person.validate.errors ?? [])
        }
    },
}
